import { Mail, MapPin, Phone } from "lucide-react";
import { PageIntro, PublicPage, SectionHeading } from "@/components/public-page";

export default function ConnectPage() {
  return (
    <PublicPage>
      <PageIntro eyebrow="Connect" title="Bring us a challenge, idea, or question." titleClassName="text-4xl sm:text-5xl lg:text-6xl" description="Tell us what you are trying to move forward. We will help find the right SAN TECH path." />
      <section className="px-6 py-20 sm:px-10 lg:px-16 lg:py-28"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[0.8fr_1.2fr]"><div><SectionHeading eyebrow="Request Demo" title="One clear next step." /><div className="mt-10 space-y-5 text-sm text-slate-600"><p className="flex items-center gap-3"><Mail className="size-4 text-brand-secondary" />info@santechinnovate.com</p><p className="flex items-center gap-3"><Phone className="size-4 text-brand-secondary" />Talk to SAN TECH</p><p className="flex items-center gap-3"><MapPin className="size-4 text-brand-secondary" />Kigali, Rwanda</p></div></div><form className="grid gap-5 rounded-xl border border-slate-200 bg-white p-7 shadow-[0_20px_60px_rgba(15,23,42,0.06)] sm:grid-cols-2 sm:p-10"><label className="grid gap-2 text-xs font-bold text-slate-700">Name<input required name="name" className="h-12 rounded-xl border border-slate-200 bg-slate-50 px-4 font-normal outline-none focus:border-brand-secondary" /></label><label className="grid gap-2 text-xs font-bold text-slate-700">Email<input required type="email" name="email" className="h-12 rounded-xl border border-slate-200 bg-slate-50 px-4 font-normal outline-none focus:border-brand-secondary" /></label><label className="grid gap-2 text-xs font-bold text-slate-700">Organization<input name="organization" className="h-12 rounded-xl border border-slate-200 bg-slate-50 px-4 font-normal outline-none focus:border-brand-secondary" /></label><label className="grid gap-2 text-xs font-bold text-slate-700">Inquiry type<select name="type" className="h-12 rounded-xl border border-slate-200 bg-slate-50 px-4 font-normal outline-none focus:border-brand-secondary"><option>Product inquiry</option><option>Service inquiry</option><option>Training</option><option>E-Visitors demo</option><option>Partnership</option><option>General inquiry</option></select></label><label className="grid gap-2 text-xs font-bold text-slate-700 sm:col-span-2">Message<textarea required name="message" rows={6} className="rounded-xl border border-slate-200 bg-slate-50 p-4 font-normal outline-none focus:border-brand-secondary" /></label><button type="submit" className="h-12 rounded-xl bg-brand-secondary px-6 text-sm font-bold text-white transition-colors hover:bg-[#1519ad] sm:col-span-2">Send inquiry</button></form></div></section>
    </PublicPage>
  );
}
