import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { PageIntro, PublicPage, SectionHeading } from "@/components/public-page";

const roles = ["Trainee", "Intern", "Researcher", "Seminar participant", "Delegation member", "Mentor", "Trainer", "Volunteer", "Partner", "Community member"];

export default async function JoinTheCommunityPage({ searchParams }: { searchParams: Promise<{ course?: string }> }) {
  const { course } = await searchParams;

  return (
    <PublicPage>
      <PageIntro eyebrow="Join the hub" title="Become part of the innovation ecosystem." description="Choose how you want to learn, contribute, partner, or help more people move forward." actions={[{ label: "Start registration", href: "#registration" }, { label: "Browse courses", href: "/san-hub/courses", tone: "secondary" }]} />
      <section className="px-6 py-14 sm:px-10 lg:px-16 lg:py-20"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Registration options" title="Choose your place in the work." description="Start with the path that fits you. You can add your programme, education, and experience details in the registration form." /><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{roles.map((role, index) => <Link key={role} href="#registration" className="group rounded-xl border border-slate-200 bg-white p-5 shadow-[0_12px_30px_rgba(7,11,36,0.06)] transition-all hover:-translate-y-1 hover:border-brand-secondary/30 hover:shadow-[0_18px_38px_rgba(7,11,36,0.12)]"><span className="text-xs font-black text-brand-secondary">{String(index + 1).padStart(2, "0")}</span><h3 className="font-exo mt-8 text-lg font-bold leading-tight tracking-[-0.02em]">Join as a {role}</h3><span className="mt-4 inline-flex items-center gap-2 text-xs font-bold text-slate-400 transition-colors group-hover:text-brand-secondary">Continue <ArrowUpRight className="size-3.5" /></span></Link>)}</div></div></section>
      <section id="registration" className="bg-[#e4eaf3] px-6 py-14 sm:px-10 lg:px-16 lg:py-20"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[0.85fr_1.15fr] lg:items-start"><SectionHeading eyebrow={course ? "Course application" : "Community registration"} title={course ? `Apply for ${course}.` : "Your next chapter starts with a few details."} description={course ? "Share your details and the SAN HUB team will follow up with the next steps for this course." : "The SAN HUB registration flow connects beneficiaries, programmes, cohorts, and participation in one place."} /><form className="grid max-w-2xl gap-4 rounded-xl border border-slate-200 bg-white p-6 shadow-[0_18px_45px_rgba(7,11,36,0.10)] sm:grid-cols-2 sm:p-8"><input required placeholder="Full name" className="h-12 rounded-xl border border-slate-200 bg-slate-50 px-4 outline-none focus:border-brand-secondary" /><input required type="email" placeholder="Email address" className="h-12 rounded-xl border border-slate-200 bg-slate-50 px-4 outline-none focus:border-brand-secondary" /><input required type="tel" placeholder="Phone number" className="h-12 rounded-xl border border-slate-200 bg-slate-50 px-4 outline-none focus:border-brand-secondary" /><input required placeholder="Country" className="h-12 rounded-xl border border-slate-200 bg-slate-50 px-4 outline-none focus:border-brand-secondary" /><select required defaultValue="" className="h-12 rounded-xl border border-slate-200 bg-slate-50 px-4 outline-none focus:border-brand-secondary"><option value="" disabled>Participation type</option>{roles.map((role) => <option key={role}>{role}</option>)}</select><input defaultValue={course ?? ""} placeholder="Course or programme" className="h-12 rounded-xl border border-slate-200 bg-slate-50 px-4 outline-none focus:border-brand-secondary" /><input placeholder="Institution or organization" className="h-12 rounded-xl border border-slate-200 bg-slate-50 px-4 outline-none focus:border-brand-secondary sm:col-span-2" /><textarea placeholder="Tell us what you want to learn or contribute." rows={4} className="rounded-xl border border-slate-200 bg-slate-50 p-4 outline-none focus:border-brand-secondary sm:col-span-2" /><button type="submit" className="h-12 rounded-xl bg-[#0c1230] px-6 text-sm font-bold text-white transition-colors hover:bg-brand-secondary sm:col-span-2">Continue registration</button></form></div></section>
    </PublicPage>
  );
}
