export const sanHubExploreRoutes = [
  { id: "learn", label: "Learn", description: "Technology and digital skills.", title: "Learn technology that becomes useful capability.", pageDescription: "Build practical skills through courses, guided practice, and projects that give you something real to show.", focus: ["Technology and digital skills", "Courses and guided learning", "Practical projects", "A clearer next step"] },
  { id: "build", label: "Build", description: "Practical projects and prototypes.", title: "Turn a difficult question into a working possibility.", pageDescription: "Move from an idea to a prototype with structure, feedback, technical support, and people who build in the real world.", focus: ["Project development", "Prototyping and testing", "Mentorship and feedback", "Practical delivery habits"] },
  { id: "innovate", label: "Innovate", description: "Challenges, research, and invention.", title: "Create the evidence behind a better solution.", pageDescription: "Explore challenges, applied research, and invention pathways that help promising ideas become tested directions.", focus: ["Innovation challenges", "Applied research", "Proof-of-concept work", "Technology experimentation"] },
  { id: "launch", label: "Launch", description: "Startups and technology products.", title: "Give a promising product a path to market.", pageDescription: "Shape a startup or technology product through validation, product development, partnerships, and commercialization support.", focus: ["Startup development", "Product validation", "Venture building", "Commercialization support"] },
  { id: "connect", label: "Connect", description: "Mentors, experts, and industry.", title: "Find the people who can move the work forward.", pageDescription: "Connect with mentors, experts, institutions, industry partners, and peers who bring context, experience, and opportunity.", focus: ["Mentors and experts", "Industry engagement", "Institutional partnerships", "Community and peer learning"] },
  { id: "work", label: "Work", description: "Internships, jobs, and career opportunities.", title: "Move from capability into opportunity.", pageDescription: "Find practical routes into internships, apprenticeships, jobs, and career guidance across the SAN TECH ecosystem.", focus: ["Internships", "Apprenticeships", "Career guidance", "Employment pathways"] },
  { id: "research", label: "Research", description: "Applied research and experimentation.", title: "Research what technology can make possible.", pageDescription: "Work on meaningful questions through applied research, experimentation, documentation, and product development.", focus: ["Research systems", "Technical investigation", "Innovation and R&D", "Research-to-product pathways"] },
  { id: "commercialize", label: "Commercialize", description: "Turn solutions into sustainable businesses.", title: "Turn a useful solution into lasting value.", pageDescription: "Build the partnerships, product thinking, and operating direction needed to turn solutions into sustainable businesses.", focus: ["Market readiness", "Product and business strategy", "Partnership development", "Sustainable growth"] },
] as const;

export type SanHubExploreRouteId = (typeof sanHubExploreRoutes)[number]["id"];

export function getSanHubExploreRoute(id: string) {
  return sanHubExploreRoutes.find((route) => route.id === id);
}
