export const navigation = [
  { label: "HOME", href: "/", iconName: "Home" },
  { label: "OUR STORY", href: "/our-story", iconName: "Info" },
  { label: "INNOVATION LAB", href: "/innovation-lab", iconName: "Zap" },
  { label: "SAN HUB", href: "/san-hub", iconName: "GraduationCap" },
  { label: "E-VISITORS", href: "/e-visitors", iconName: "ShieldCheck" },
  { label: "TECH PULSE", href: "/tech-pulse", iconName: "Radio" },
  { label: "CONNECT", href: "/connect", iconName: "Mail" },
];

export const heroCTAs = [
  { label: "Explore Our Solutions", href: "/innovation-lab" },
  { label: "Join SAN HUB", href: "/san-hub" },
  { label: "Discover E-Visitors", href: "/e-visitors" },
];

export const dynamicStats = [
  { value: "10k+", label: "Beneficiaries Empowered", target: 10000, suffix: "k+" },
  { value: "12+", label: "Countries Reached", target: 12, suffix: "+" },
  { value: "47+", label: "Institutions Served", target: 47, suffix: "+" },
  { value: "25+", label: "Startups & Projects", target: 25, suffix: "+" },
  { value: "350+", label: "Jobs Created", target: 350, suffix: "+" },
  { value: "2,500+", label: "Training Graduates", target: 2500, suffix: "+" },
];

export const whatWeDo = [
  {
    number: "01",
    title: "Software Development",
    description: "Custom software solutions, web and mobile applications built for your unique needs.",
    category: "Engineering",
    href: "/innovation-lab",
  },
  {
    number: "02",
    title: "AI Solutions",
    description: "Intelligent systems and machine learning solutions to help you work smarter and faster.",
    category: "Intelligence",
    href: "/innovation-lab",
  },
  {
    number: "03",
    title: "IoT & Embedded Systems",
    description: "Connected devices and smart systems for real-time monitoring, control, and automation.",
    category: "Hardware & IoT",
    href: "/innovation-lab",
  },
  {
    number: "04",
    title: "Cybersecurity",
    description: "Protecting your data, systems and digital assets with advanced security solutions.",
    category: "Security",
    href: "/innovation-lab",
  },
  {
    number: "05",
    title: "Digital Transformation",
    description: "Modernize your operations, improve efficiency and unlock new opportunities.",
    category: "Enterprise",
    href: "/innovation-lab",
  },
  {
    number: "06",
    title: "IT Infrastructure",
    description: "Reliable and scalable infrastructure for high performance and business continuity.",
    category: "Infrastructure",
    href: "/innovation-lab",
  },
  {
    number: "07",
    title: "Capacity Building",
    description: "Training, mentorship and skills development for a future-ready workforce.",
    category: "SAN HUB",
    href: "/san-hub",
  },
  {
    number: "08",
    title: "Innovation & Research",
    description: "Turning ideas into solutions through research, experimentation and collaboration.",
    category: "R&D",
    href: "/innovation-lab",
  },
  {
    number: "09",
    title: "Systems Integration",
    description: "Seamless integration of your systems, devices and platforms for greater value.",
    category: "Integration",
    href: "/innovation-lab",
  },
  {
    number: "10",
    title: "Consultancy",
    description: "Expert guidance and strategic advice to help you achieve your technology goals.",
    category: "Advisory",
    href: "/connect",
  },
];

export const products = [
  {
    title: "E-Visitors",
    slug: "e-visitors",
    tagline: "Smart Visitor, Access & Attendance Management Platform",
    description: "Automated visitor registration, ID/OCR scanning, VIP tracking, and real-time security intelligence for public and private institutions.",
    category: "Security & Operations",
    badge: "Flagship Product",
    stats: "47+ Deployments",
    href: "/e-visitors",
    features: ["ID/OCR Scanning", "VIP Management", "Access Cards", "Gate Control", "Audit Logs"],
  },
  {
    title: "SAN TRACK",
    slug: "san-track",
    tagline: "Intelligent Fleet, Asset & Logistics Tracking",
    description: "Real-time IoT-powered tracking and telemetry platform for vehicles, field assets, and supply chain visibility.",
    category: "IoT & Telemetry",
    badge: "Enterprise IoT",
    stats: "Real-time Telemetry",
    href: "/innovation-lab",
    features: ["Live GPS Mapping", "Fuel Monitoring", "Driver Analytics", "Geo-Fencing"],
  },
  {
    title: "SAN BOOK",
    slug: "san-book",
    tagline: "Digital Library, Academic & Learning Management",
    description: "Comprehensive institutional e-learning and digital library repository for schools, universities, and training institutes.",
    category: "EdTech",
    badge: "EdTech Platform",
    stats: "15,000+ Readers",
    href: "/innovation-lab",
    features: ["Digital Content Repository", "Courseware", "Offline Sync", "Student Analytics"],
  },
  {
    title: "REVIXSAN",
    slug: "revixsan",
    tagline: "Enterprise Revenue, Billing & Audit Management",
    description: "Integrated financial workflow platform designed for transparent revenue collection, invoice verification, and audit tracking.",
    category: "FinTech & GovTech",
    badge: "Financial Systems",
    stats: "100% Audit Ready",
    href: "/innovation-lab",
    features: ["Automated Invoicing", "Tax Reconciliation", "Multi-Gateway Support", "Audit Trails"],
  },
  {
    title: "SANVERSE",
    slug: "sanverse",
    tagline: "Virtual Innovation & Immersive Simulation Lab",
    description: "Virtual and augmented reality platform for engineering simulations, industrial training, and interactive digital twins.",
    category: "Immersive Tech",
    badge: "Spatial Computing",
    stats: "Interactive 3D",
    href: "/innovation-lab",
    features: ["VR Training", "Digital Twins", "3D Prototyping", "Remote Collaboration"],
  },
];

export const clientLogos = [
  { name: "National Bank of Rwanda (BNR)", role: "Client / Institutional" },
  { name: "CIMERWA", role: "Client / Industrial" },
  { name: "KIGEME District Hospital", role: "Client / Healthcare" },
  { name: "NIRDA", role: "Client / Research & Industry" },
  { name: "ADARWA", role: "Client / Enterprise" },
  { name: "HIIL / COMMUNITAS", role: "Client / Justice & Innovation" },
];

export const sectors = [
  "Government",
  "Education",
  "Healthcare",
  "Tourism & Hospitality",
  "Manufacturing",
  "Agriculture",
  "Transport",
  "Financial Services",
  "Security",
  "SMEs",
  "NGOs",
];

export const techPulseItems = [
  {
    id: "opp-1",
    type: "Opportunities",
    badge: "Fellowship",
    title: "SAN HUB Tech & AI Innovation Fellowship 2026",
    description: "Full scholarship and incubation for African developers building high-impact AI and embedded systems.",
    deadline: "Open until Nov 30, 2026",
    link: "/san-hub",
  },
  {
    id: "news-1",
    type: "News",
    badge: "Milestone",
    title: "SAN TECH Wins Best Exhibitor at ICT & Innovation Expo 2026",
    description: "Recognized for pioneering digital transformation and the rapid deployment of E-Visitors across Rwanda.",
    deadline: "Published Sep 2026",
    link: "/tech-pulse",
  },
  {
    id: "tender-1",
    type: "Tenders",
    badge: "Procurement",
    title: "Tender Ref: ST-2026-T04: IoT Sensor Hardware Supply",
    description: "Invitation for certified hardware suppliers to bid on environmental and telemetry sensor modules.",
    deadline: "Deadline: Oct 15, 2026",
    link: "/tech-pulse",
  },
  {
    id: "event-1",
    type: "Events",
    badge: "Summit",
    title: "African Innovation & Digital Systems Summit 2026",
    description: "Join industry leaders, policymakers, and engineering leaders discussing local manufacturing and tech scale.",
    deadline: "Date: Nov 12, 2026 · Kigali",
    link: "/tech-pulse",
  },
];

export const sanHubCourses = [
  {
    id: "software-engineering",
    title: "Full-Stack Software Engineering",
    category: "Software Engineering",
    duration: "16 Weeks",
    mode: "Hybrid / Kigali Campus",
    level: "Intermediate to Advanced",
    description: "Comprehensive modern stack engineering covering Next.js, TypeScript, PostgreSQL, REST/GraphQL APIs, and cloud deployment.",
    modules: 4,
  },
  {
    id: "ai-machine-learning",
    title: "Applied AI & Machine Learning",
    category: "AI & Machine Learning",
    duration: "12 Weeks",
    mode: "Online & Weekend Labs",
    level: "All Levels",
    description: "Practical computer vision, NLP, automated analytics, and LLM integrations built for real African enterprise problems.",
    modules: 4,
  },
  {
    id: "cybersecurity-defense",
    title: "Cybersecurity & Threat Intelligence",
    category: "Cybersecurity",
    duration: "10 Weeks",
    mode: "Intensive Labs",
    level: "Intermediate",
    description: "Network security, vulnerability assessment, penetration testing, RBAC, and zero-trust infrastructure protocols.",
    modules: 3,
  },
  {
    id: "iot-embedded-systems",
    title: "IoT & Embedded Hardware Systems",
    category: "IoT & Hardware",
    duration: "12 Weeks",
    mode: "Hands-on Workshop",
    level: "Beginner to Advanced",
    description: "Microcontrollers, telemetry protocols (MQTT/HTTP), circuit design, sensor networks, and edge computing.",
    modules: 4,
  },
];

export const timelineEvents = [
  { year: "2019", title: "SAN TECH Founded", description: "Established with a bold vision to engineer homegrown technology solutions and build African digital capacity." },
  { year: "2022", title: "Training & Innovation Programs", description: "Launched flagship community empowerment cohorts and established structured digital learning pathways." },
  { year: "2023", title: "SAN HUB Expansion", description: "Scaled the innovation ecosystem to reach over 10,000 beneficiaries and hundreds of active developers." },
  { year: "2024", title: "Digital Solutions Expansion", description: "Nationwide rollout of E-Visitors and enterprise platforms across 47+ institutions." },
  { year: "2026", title: "African Innovation Ecosystem", description: "Leading the continent in smart technologies, software engineering, and digital systems manufacturing." },
];
