import type { LucideIcon } from "lucide-react";
import { BrainCircuit, Cloud, Code2, Database, GitBranch, Globe2, LockKeyhole, Network, Radio, Wrench } from "lucide-react";

export type TechnologyCategory = { id: string; label: string; description: string; items: string[]; icon?: LucideIcon };

export const technologyCategories: TechnologyCategory[] = [
  { id: "programming-languages", label: "Programming Languages", description: "A broad catalog of languages used across web, mobile, enterprise, systems, data, scientific, embedded, and emerging technology work.", items: [
    "Python", "Java", "JavaScript", "TypeScript", "PHP", "C", "C++", "C#", "Go", "Rust", "Kotlin", "Swift", "Dart", "Ruby", "R", "Scala", "Objective-C", "Visual Basic", "SQL", "PL/SQL", "T-SQL", "HTML5", "CSS3", "Sass", "Bash / Shell", "PowerShell", "Assembly", "Ada", "ALGOL", "Apex", "ABAP", "COBOL", "Fortran", "Delphi / Object Pascal", "F#", "Groovy", "Haskell", "Clojure", "Common Lisp", "Scheme", "Elixir", "Erlang", "Elm", "Julia", "Lua", "MATLAB", "Perl", "Raku", "Prolog", "OCaml", "Crystal", "D", "Nim", "Zig", "V", "Solidity", "GDScript", "Haxe", "Hack", "SAS", "Verilog", "VHDL", "WebAssembly"
  ], icon: Code2 },
  { id: "web-application-development", label: "Web & Application Development", description: "Frameworks and patterns for accessible web platforms, APIs, enterprise applications, and progressive digital services.", items: ["React.js", "Next.js", "Angular", "Vue.js", "Node.js", "Express.js", "Laravel", "Django", "FastAPI", "Spring Boot", ".NET / ASP.NET", "REST APIs", "GraphQL", "Progressive Web Apps (PWA)"], icon: Globe2 },
  { id: "mobile-development", label: "Mobile Development", description: "Mobile technologies for reliable applications and connected services across the devices people use every day.", items: ["Flutter", "Android / Kotlin", "React Native", "Java", "Firebase", "Mobile REST/API integration"], icon: Radio },
  { id: "artificial-intelligence", label: "Artificial Intelligence & Machine Learning", description: "Tools and methods for intelligent automation, prediction, language, recommendations, and decision support.", items: ["Python AI/ML ecosystem", "TensorFlow", "PyTorch", "Scikit-learn", "OpenCV", "Computer Vision", "OCR", "Natural Language Processing (NLP)", "Generative AI", "Large Language Model (LLM) integration", "Predictive analytics", "Recommendation systems", "AI chatbots and virtual assistants"], icon: BrainCircuit },
  { id: "ocr-computer-vision", label: "OCR & Computer Vision", description: "Image and document technologies for identity, access control, visitor management, vehicle systems, and digitization.", items: ["Tesseract OCR", "OpenCV", "ID/passport/document recognition", "Face/image processing", "Vehicle/license-plate recognition", "Camera-based monitoring", "Document digitization", "Image classification"], icon: Wrench },
  { id: "databases", label: "Databases", description: "Data storage, design, optimization, recovery, and analytics foundations for dependable digital systems.", items: ["MySQL", "PostgreSQL", "Microsoft SQL Server", "SQLite", "MongoDB", "Redis", "Firebase Firestore", "Database design and optimization", "Data warehousing", "Backup and recovery"], icon: Database },
  { id: "iot-embedded", label: "IoT & Embedded Systems", description: "Connected devices, sensors, embedded platforms, and communication protocols for smart monitoring and automation.", items: ["Arduino", "ESP32", "ESP8266", "Raspberry Pi", "STM32", "Sensors and actuators", "RFID", "NFC", "GPS/GNSS", "GSM/4G/5G", "LoRa/LoRaWAN", "MQTT", "Industrial IoT", "Smart monitoring systems", "Embedded C/C++"], icon: Radio },
  { id: "cybersecurity", label: "Cybersecurity", description: "Security practices that protect systems, applications, identities, networks, devices, and information.", items: ["Network security", "Application security", "Identity and Access Management", "Role-Based Access Control (RBAC)", "Encryption", "Secure API development", "Vulnerability assessment", "Penetration testing", "Security monitoring", "SIEM integration", "Endpoint security", "Firewall technologies", "Security auditing", "Digital forensics"], icon: LockKeyhole },
  { id: "networking-infrastructure", label: "Networking & Infrastructure", description: "The networks, servers, connectivity, monitoring, and physical integrations that keep technology available and useful.", items: ["TCP/IP", "LAN/WAN", "VLAN", "VPN", "Wi-Fi", "Routing and switching", "Network monitoring", "DNS/DHCP", "Active Directory", "Linux servers", "Windows Server", "Virtualization", "Structured cabling", "CCTV and physical security integration"], icon: Network },
  { id: "cloud-devops", label: "Cloud & DevOps", description: "Cloud platforms and delivery practices for deploying, scaling, monitoring, and continuously improving technology.", items: ["AWS", "Microsoft Azure", "Google Cloud", "Docker", "Kubernetes", "Git", "GitHub", "GitLab", "CI/CD", "Linux", "Nginx", "Apache", "Cloud databases", "Cloud storage", "Server deployment and monitoring"], icon: Cloud },
  { id: "development-collaboration-tools", label: "Development & Collaboration Tools", description: "Tools that help teams plan, design, build, test, document, and deliver technology together.", items: ["Git / GitHub / GitLab", "Visual Studio Code", "IntelliJ IDEA", "Android Studio", "Postman", "Docker", "Jira", "Trello", "Figma", "Microsoft 365", "Linux", "Windows Server"], icon: GitBranch },
];
